¿
Ÿ
C
Placeholder
output"dtype"
dtypetype"
shapeshape:
:
Sub
x"T
y"T
z"T"
Ttype:
2	"serve*1.13.12
b'unknown'ş
\
aPlaceholder*
shape:ÿÿÿÿÿÿÿÿÿ*
dtype0*#
_output_shapes
:ÿÿÿÿÿÿÿÿÿ
\
bPlaceholder*
shape:ÿÿÿÿÿÿÿÿÿ*
dtype0*#
_output_shapes
:ÿÿÿÿÿÿÿÿÿ
<
cSubab*
T0*#
_output_shapes
:ÿÿÿÿÿÿÿÿÿ"*™
substract_demo†
!
input_a
a:0ÿÿÿÿÿÿÿÿÿ
!
input_b
b:0ÿÿÿÿÿÿÿÿÿ"
output_c
c:0ÿÿÿÿÿÿÿÿÿtensorflow/serving/predict